### ISSUE TITLE
Schema REST API causes Internal Server Error (psycopg2)

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-author#54]
### Expected behaviour
Survey screen displays surveys and questionnaires

### Actual behaviour
Internal Server Error is reported

### Steps to reproduce the behaviour
- Login
- See error

#### Browser
All 

#### Operating System
All

### Screenshot
![image](https://cloud.githubusercontent.com/assets/14041600/17603885/0d27ef10-600b-11e6-971d-11b1a4d0fb2b.png)

### EB Stack Trace

```
-------------------------------------
/var/log/httpd/error_log
-------------------------------------
[Thu Aug 11 20:28:08.748719 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
[Thu Aug 11 20:28:08.748721 2016] [:error] [pid 3250]     response = self.process_exception_by_middleware(e, request)
[Thu Aug 11 20:28:08.748723 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
[Thu Aug 11 20:28:08.748725 2016] [:error] [pid 3250]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Aug 11 20:28:08.748735 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Thu Aug 11 20:28:08.748737 2016] [:error] [pid 3250]     return view_func(*args, **kwargs)
[Thu Aug 11 20:28:08.748739 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
[Thu Aug 11 20:28:08.748741 2016] [:error] [pid 3250]     return self.dispatch(request, *args, **kwargs)
[Thu Aug 11 20:28:08.748763 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
[Thu Aug 11 20:28:08.748767 2016] [:error] [pid 3250]     response = self.handle_exception(exc)
[Thu Aug 11 20:28:08.748769 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
[Thu Aug 11 20:28:08.748771 2016] [:error] [pid 3250]     response = handler(request, *args, **kwargs)
[Thu Aug 11 20:28:08.748773 2016] [:error] [pid 3250]   File "/opt/python/current/app/qBuilder/apps/rest_api/views.py", line 73, in get
[Thu Aug 11 20:28:08.748775 2016] [:error] [pid 3250]     return self.list(request, *args, **kwargs)
[Thu Aug 11 20:28:08.748777 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/mixins.py", line 48, in list
[Thu Aug 11 20:28:08.748779 2016] [:error] [pid 3250]     return Response(serializer.data)
[Thu Aug 11 20:28:08.748781 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/serializers.py", line 674, in data
[Thu Aug 11 20:28:08.748783 2016] [:error] [pid 3250]     ret = super(ListSerializer, self).data
[Thu Aug 11 20:28:08.748785 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/serializers.py", line 239, in data
[Thu Aug 11 20:28:08.748787 2016] [:error] [pid 3250]     self._data = self.to_representation(self.instance)
[Thu Aug 11 20:28:08.748789 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/rest_framework/serializers.py", line 614, in to_representation
[Thu Aug 11 20:28:08.748791 2016] [:error] [pid 3250]     self.child.to_representation(item) for item in iterable
[Thu Aug 11 20:28:08.748793 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/models/query.py", line 258, in __iter__
[Thu Aug 11 20:28:08.748795 2016] [:error] [pid 3250]     self._fetch_all()
[Thu Aug 11 20:28:08.748796 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
[Thu Aug 11 20:28:08.748798 2016] [:error] [pid 3250]     self._result_cache = list(self.iterator())
[Thu Aug 11 20:28:08.748800 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/models/query.py", line 52, in __iter__
[Thu Aug 11 20:28:08.748802 2016] [:error] [pid 3250]     results = compiler.execute_sql()
[Thu Aug 11 20:28:08.748804 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
[Thu Aug 11 20:28:08.748806 2016] [:error] [pid 3250]     cursor.execute(sql, params)
[Thu Aug 11 20:28:08.748808 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
[Thu Aug 11 20:28:08.748810 2016] [:error] [pid 3250]     return super(CursorDebugWrapper, self).execute(sql, params)
[Thu Aug 11 20:28:08.748812 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
[Thu Aug 11 20:28:08.748814 2016] [:error] [pid 3250]     return self.cursor.execute(sql, params)
[Thu Aug 11 20:28:08.748816 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
[Thu Aug 11 20:28:08.748821 2016] [:error] [pid 3250]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Thu Aug 11 20:28:08.748823 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
[Thu Aug 11 20:28:08.748825 2016] [:error] [pid 3250]     raise value.with_traceback(tb)
[Thu Aug 11 20:28:08.748827 2016] [:error] [pid 3250]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
[Thu Aug 11 20:28:08.748829 2016] [:error] [pid 3250]     return self.cursor.execute(sql, params)
[Thu Aug 11 20:28:08.748831 2016] [:error] [pid 3250] django.db.utils.ProgrammingError: column rest_api_schemameta.modified does not exist
[Thu Aug 11 20:28:08.748833 2016] [:error] [pid 3250] LINE 1: ...mameta"."eq_id", "rest_api_schemameta"."created", "rest_api_...
[Thu Aug 11 20:28:08.748835 2016] [:error] [pid 3250]                                                              ^
[Thu Aug 11 20:28:08.748843 2016] [:error] [pid 3250] 
[Thu Aug 11 20:28:39.262819 2016] [:error] [pid 3249] Internal Server Error: /api/v1/schema/
[Thu Aug 11 20:28:39.262844 2016] [:error] [pid 3249] Traceback (most recent call last):
[Thu Aug 11 20:28:39.262847 2016] [:error] [pid 3249]   File "/opt/python/run/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
[Thu Aug 11 20:28:39.262849 2016] [:error] [pid 3249]     return self.cursor.execute(sql, params)
[Thu Aug 11 20:28:39.262851 2016] [:error] [pid 3249] psycopg2.ProgrammingError: column rest_api_schemameta.modified does not exist
[Thu Aug 11 20:28:39.262853 2016] [:error] [pid 3249] LINE 1: ...mameta"."eq_id", "rest_api_schemameta"."created", "rest_api_...
[Thu Aug 11 20:28:39.262856 2016] [:error] [pid 3249]                                                              ^
```

**Comment by dhilton** [comment]
As @warrenbailey said on Friday this looks like a migrations issue - the change to add modified field was merged into the previous schema migration so the migration to the new schema was not run. Answer is to blat the environment and rebuild. Just need to login to Jenkins to run destroy and create jobs.

**Comment by collisdigital** [comment]
Confirmed now working after latest re-deployment. Closing.
